routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/cat', function () {
//     // Artisan::call('migrate');
//     return view('front-end.pages.sigleview.blade');
// });



Route::get('/', function () {
    // Artisan::call('migrate');
    return view('front-end.coming-soon.index');
})->name('index');

Route::get('/contact', function () {
    // Artisan::call('migrate');
    return view('front-end.pages.contact');
})->name('contact');
Route::get('post-publish', 'Admin\PostPublishController@postpublish');


Route::get('/config-cache',function(){
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    Artisan::call('queue:restart');
});

Route::get('/file',function(){
    Artisan::call('queue:work',['--stop-when-empty' => true]);


});

Route::get('/mig', function () {
    Artisan::call('migrate');
    // return 'success';
    // return view('front-end.pages.sigleview.blade');
});

Route::get('/test', function () {
    

    for ($i=0; $i <count(pageTokens()) ; $i++) { 
        // \App\Jobs\SendPost::dispatch(pageTokens()[$i]);

        Toolkito\Larasap\SendTo::Facebook(
            'link',
            [
                'link' =>'http://topcini.com',
                'message' => ' Added at Topcini',
                'page_access_token' => pageTokens()[$i]
            ]
        );
        

    }

    // \App\Jobs\SendPost::dispatch();
});

// Route::get('config-cache',function(){
//     Artisan::call('config:cache');
//     Artisan::call('view:clear');
//     return 'success';
// });


// Auth::routes();


$this->get('aurait', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('aurait', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');


Route::get('/home', 'HomeController@index')->name('home');

Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');


Route::name('password.edit')->get('password-change', 'Admin\UserController@passwordReset');
Route::name('password.update')->post('password-change', 'Admin\UserController@postPasswordReset');

Route::name('password.editadmin')->get('/password-change', 'Admin\UserController@passwordResetadmin');
Route::name('password.update')->post('/password-change', 'Admin\UserController@postPasswordReset');

Route::name('password.request')->get('/password-request', 'Admin\UserController@passwordChange');
Route::name('password.request')->post('/password-request', 'Admin\UserController@postPasswordChange');

Route::group(['prefix'=>'admin','middleware' => ['auth']], function(){
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('comments', 'Admin\CommentsController');
    Route::resource('subscribers', 'Admin\SubscriberController');
    Route::resource('contacts', 'Admin\ContactController');
    Route::resource('post', 'Admin\PostController');
    Route::get('search', 'Front\TechFascinoController@backendsearch')->name('search');

    
   
});

Route::group(['middleware' => ['auth']], function(){
   
    Route::resource('permission', 'Admin\PermissionController');
    Route::resource('role', 'Admin\RoleController');
    Route::resource('user', 'Admin\UserController');
});



// Route::get('/page', 'GraphController@publishToPage')->name('fb');

Route::post('child', 'Admin\PostController@child')->name('child');
// ///////////////////////////////////////////////////////////////

//// Route::get('/', 'Front\TechFascinoController@index')->name('index');
Route::post('savecomment', 'Front\TechFascinoController@savecomment')->name('savecomment');
Route::post('subscribe', 'Front\TechFascinoController@subscribe')->name('subscribe');

Route::post('contact', 'Front\TechFascinoController@contact')->name('contactform');

Route::get('searchresults', 'Front\TechFascinoController@searchresults')->name('searchresults');

Route::get('/{slug?}', 'Front\TechFascinoController@categoryview')->name('category');
Route::get('/{categoryslug?}/{postslug?}', 'Front\TechFascinoController@singlepost')->name('singlepost');

// Route::get('/{category?}/{drama?}', 'Front\TopciniController@singledrama')->name('singledrama');

// Route::get('/{category?}/{drama?}/{postdrama?}', 'Front\TopciniController@singleserial')->name('singleserial');

// Route::post('autocomplete', 'Front\TopciniController@autocomplete')->name('autocomplete');

Route::get('test-email', 'Admin\JobController@processQueue');

Route::get('/', 'Front\TechFascinoController@index')->name('index');

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    //
}

app/Http/Controllers/Admin/CommentsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Authorizable;
use App\Models\Comment;

class CommentsController extends Controller
{
    use Authorizable;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $comments = Comment::all();
        return view('back-end.comments.index',compact('comments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $comment = Comment::find($id);
        return view('back-end.comments.edit',compact('comment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      
        $comment = Comment::find($id);
        $comment->status = $request->status;
        $comment->save();

        return redirect()->back();
       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $comment = Comment::find($id);     
        $comment->delete();
        return response()->json([
            'success'=>true,
            'message'=>'Deleted Successful',
        ]);
    }
}

resources/views/back-end/comments/edit.blade.php
{!! Form::model($comment,['route' => ['comments.update',$comment->id], 'method' => 'post','files' => true]) !!}
@method('PUT') 
@foreach ($errors->all() as $error)
    <div class="form-group row" style="color: red;font-size: 15px;text-align: center;">    
        {{ $error }}
    </div>
@endforeach                          
 @include('back-end.comments.form')
<div class="">
   
    <button class="btn btn-primary">Save</button>
</div><!-- form-layout-footer -->
{{Form::close()}}

resources/views/back-end/comments/form.blade.php
<div class="form-group">
    {!!Form::label('status', 'Status')!!}
    {!!Form::select('status',systemValues('status'),null,['class' =>'form-control col-12'])!!}
</div>

resources/views/back-end/comments/index.blade.php
@extends('back-end.template')
@section('title','List of Comments')
@section('content')

<div class="page-header">
    <h3 class="page-title">
        List of Comments
    </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Comments</a></li>
        <li class="breadcrumb-item active" aria-current="page">All Comments</li>
        </ol>
    </nav>
    </div>
    <div class="row">  
        <div class="col-md-12">
            <div class="card card-default card-demo" id="cardChart9">
                <div class="card-header">
                    <div class="float-right">
                       
                    </div>
                    <div class="card-title">List of Comments</div>
                </div>
                <div class="card-wrapper collapse show">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table display nowrap" datatable style="font-size:12px" id="commentstable">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Comments</th>
                                    <th>Status</th>
                                    @can('edit_comments')
                                        <th>Action</th>
                                    @endcan
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($comments as $comment)
                                    <tr>
                                        <td>{{$comment->name}}</td>
                                        <td>{{$comment->email}}</td>
                                        <td>{{ $comment->comment}}</td>
                                        <td>{{ $comment->status}}</td>
                                        @can('edit_comments')
                                        <td>
                                            <a href="{{route('comments.edit',$comment->id)}}" class="btn btn-sm btn-info ajax-load-modal" data-title="Comment Status"><i class="fa fa-pencil-alt"></i></a>
                                            <a href="{{route('comments.destroy',$comment->id)}}" class="btn btn-sm btn-warning ajax-delete" data-set="tr"><i class="fa fa-trash"></i></a>
                                        </td>
                                        @endcan
                                    </tr>
                                @endforeach
                            
                            </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@push('script')                    
    <script>

        $(document).ready(function () {
            $('#commentstable').DataTable({
            });
        })

    </script>
@endpush
@stop