routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/cat', function () {
//     // Artisan::call('migrate');
//     return view('front-end.pages.sigleview.blade');
// });



Route::get('/', function () {
    // Artisan::call('migrate');
    return view('front-end.coming-soon.index');
})->name('index');

Route::get('/contact', function () {
    // Artisan::call('migrate');
    return view('front-end.pages.contact');
})->name('contact');
Route::get('post-publish', 'Admin\PostPublishController@postpublish');


Route::get('/config-cache',function(){
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    Artisan::call('queue:restart');
});

Route::get('/file',function(){
    Artisan::call('queue:work',['--stop-when-empty' => true]);


});

Route::get('/mig', function () {
    Artisan::call('migrate');
    // return 'success';
    // return view('front-end.pages.sigleview.blade');
});

Route::get('/test', function () {
    

    for ($i=0; $i <count(pageTokens()) ; $i++) { 
        // \App\Jobs\SendPost::dispatch(pageTokens()[$i]);

        Toolkito\Larasap\SendTo::Facebook(
            'link',
            [
                'link' =>'http://topcini.com',
                'message' => ' Added at Topcini',
                'page_access_token' => pageTokens()[$i]
            ]
        );
        

    }

    // \App\Jobs\SendPost::dispatch();
});

// Route::get('config-cache',function(){
//     Artisan::call('config:cache');
//     Artisan::call('view:clear');
//     return 'success';
// });


// Auth::routes();


$this->get('aurait', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('aurait', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');


Route::get('/home', 'HomeController@index')->name('home');

Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');


Route::name('password.edit')->get('password-change', 'Admin\UserController@passwordReset');
Route::name('password.update')->post('password-change', 'Admin\UserController@postPasswordReset');

Route::name('password.editadmin')->get('/password-change', 'Admin\UserController@passwordResetadmin');
Route::name('password.update')->post('/password-change', 'Admin\UserController@postPasswordReset');

Route::name('password.request')->get('/password-request', 'Admin\UserController@passwordChange');
Route::name('password.request')->post('/password-request', 'Admin\UserController@postPasswordChange');

Route::group(['prefix'=>'admin','middleware' => ['auth']], function(){
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('comments', 'Admin\CommentsController');
    Route::resource('subscribers', 'Admin\SubscriberController');
    Route::resource('contacts', 'Admin\ContactController');
    Route::resource('post', 'Admin\PostController');
    Route::get('search', 'Front\TechFascinoController@backendsearch')->name('search');

    
   
});

Route::group(['middleware' => ['auth']], function(){
   
    Route::resource('permission', 'Admin\PermissionController');
    Route::resource('role', 'Admin\RoleController');
    Route::resource('user', 'Admin\UserController');
});



// Route::get('/page', 'GraphController@publishToPage')->name('fb');

Route::post('child', 'Admin\PostController@child')->name('child');
// ///////////////////////////////////////////////////////////////

//// Route::get('/', 'Front\TechFascinoController@index')->name('index');
Route::post('savecomment', 'Front\TechFascinoController@savecomment')->name('savecomment');
Route::post('subscribe', 'Front\TechFascinoController@subscribe')->name('subscribe');

Route::post('contact', 'Front\TechFascinoController@contact')->name('contactform');

Route::get('searchresults', 'Front\TechFascinoController@searchresults')->name('searchresults');

Route::get('/{slug?}', 'Front\TechFascinoController@categoryview')->name('category');
Route::get('/{categoryslug?}/{postslug?}', 'Front\TechFascinoController@singlepost')->name('singlepost');

// Route::get('/{category?}/{drama?}', 'Front\TopciniController@singledrama')->name('singledrama');

// Route::get('/{category?}/{drama?}/{postdrama?}', 'Front\TopciniController@singleserial')->name('singleserial');

// Route::post('autocomplete', 'Front\TopciniController@autocomplete')->name('autocomplete');

Route::get('test-email', 'Admin\JobController@processQueue');

Route::get('/', 'Front\TechFascinoController@index')->name('index');

app/Models/Permission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Permission extends \Spatie\Permission\Models\Permission
{
    //

    public function module()
    {
        return $this->belongsTo('App\Models\Module');
    }

    public static function defaultPermissions()
    {
        $array = [
            ['module'=>'User','name'=>'view_user','display'=>'View Users'],
            ['module'=>'User','name'=>'add_user','display'=>'Add Users'],
            ['module'=>'User','name'=>'edit_user','display'=>'Edit Users'],
            ['module'=>'User','name'=>'delete_user','display'=>'Delete Users'],

            ['module'=>'Role','name'=>'view_role','display'=>'View Roles'],
            ['module'=>'Role','name'=>'add_role','display'=>'Add Roles'],
            ['module'=>'Role','name'=>'edit_role','display'=>'Edit Roles'],
            ['module'=>'Role','name'=>'delete_role','display'=>'Delete Roles'],

            ['module'=>'Permission','name'=>'view_permission','display'=>'View Permissions'],
            ['module'=>'Permission','name'=>'add_permission','display'=>'Add Permissions'],
            ['module'=>'Permission','name'=>'edit_permission','display'=>'Edit Permissions'],
            ['module'=>'Permission','name'=>'delete_permission','display'=>'Delete Permissions'],
        ];

        return $array;
    }
}

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\{Permission,Module,Role};
use App\Authorizable;

class PermissionController extends Controller
{
    use Authorizable;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::all();
        if(request()->sync){
            if($role = Role::where('name', 'Admin')->first()) {
                $role->syncPermissions(Permission::all());
            }
            
        }
        return view('admin.permission.index',compact('permissions'));

        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.permission.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $resources = ['view','add','edit','delete'];
        if(isset($request->resource)){
            foreach($resources as $resource){
                $permission = new Permission;
                $permission->name = $resource.'_'.strtolower($request->module);
                $permission->display_name = ucfirst($resource).' '.$request->module;
                $permission->guard_name = 'web';
                $permission->module_id = Module::firstOrCreate(['name'=>$request->module])->id;
                $permission->save();
            }       
        }else{

            $permission = new Permission;
            $permission->name = $request->name;
            $permission->display_name = $request->display_name;
            $permission->guard_name = 'web';
            $permission->module_id = Module::firstOrCreate(['name'=>$request->module])->id;
            $permission->save();
        }

        if($role = Role::where('name', 'Admin')->first() ) {
            $role->syncPermissions(Permission::all());
        }
        if($role = Role::where('name', 'SAdmin')->first()) {
            $role->syncPermissions(Permission::all());
        }

        return redirect()->route('permission.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
    */

    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Permission $permission)
    {
        $permission->module_name = $permission->module->name;
        return view('admin.permission.edit',compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Permission $permission)
    {
        $permission->name = $request->name;
        $permission->display_name = $request->display_name;
        $permission->guard_name = 'web';
        $permission->module_id =  Module::firstOrCreate(['name'=>$request->module])->id;
        $permission->save();
        return redirect()->route('permission.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Permission $permission)
    {
        $permission->delete();
        if($role = Role::where('name', 'Admin')->first() ) {
            $role->syncPermissions(Permission::all());
        }
        if($role = Role::where('name', 'SAdmin')->first()) {
            $role->syncPermissions(Permission::all());
        }
        return response()->json([
            'success'=>true,
            'message'=>'Item Removed'
        ]);


    }

   

}

resources/views/admin/permission/create.blade.php
@extends('back-end.template')
@section('title','New Permissions')
@section('content')
<div class="page-header">
    <h3 class="page-title">
        New Permissions
    </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Permissions</a></li>
        <li class="breadcrumb-item active" aria-current="page">New Permissions</li>
        </ol>
    </nav>
    </div>
    <div class="row">  
        <div class="col-md-12">
            <div class="card card-default card-demo" id="cardChart9">
                <div class="card-header">
                    <div class="card-title">New permissions</div>
                </div>
                <div class="card-wrapper collapse show">
                    <div class="card-body">
                            {{Form::open(['route'=>['permission.store'],'class'=>'permission'])}}
                            @include('admin.permission.form')
                            <div class="">
                                <a class="btn btn-secondary" href="{{ route('permission.index') }}"> <i class="ion-ios-arrow-thin-left"></i> Back</a>
                                <button class="btn btn-primary">Save</button>
                            </div><!-- form-layout-footer -->
                        {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div>

@stop

resources/views/admin/permission/edit.blade.php
@extends('back-end.template')
@section('title','Edit Permissions')
@section('content')
<div class="page-header">
    <h3 class="page-title">
        Edit permission
    </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Permissions</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit permission</li>
        </ol>
    </nav>
    </div>
    <div class="row">  
        <div class="col-md-12">
            <div class="card card-default card-demo" id="cardChart9">
                <div class="card-header">
                    <div class="card-title">Edit permission - {{$permission->display_name }}</div>
                </div>
                <div class="card-wrapper collapse show">
                    <div class="card-body">
                            {{Form::open(['route'=>['permission.store'],'class'=>'permission'])}}
                            @include('admin.permission.form')
                            <div class="">
                                <a class="btn btn-secondary" href="{{ route('permission.index') }}"> <i class="ion-ios-arrow-thin-left"></i> Back</a>
                                <button class="btn btn-primary">Save</button>
                            </div><!-- form-layout-footer -->
                        {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
   
@stop

resources/views/admin/permission/form.blade.php
<div class="form-group">
    <label for="">Module</label>
    <input type="text" name="module" class="form-control" value="{{ isset($permission) ? $permission->module_name : ''}}" required>
</div>

<div class="form-group">
    <div class="row">
       
        <div class="col-sm-6">
            <label for="">Display Name</label>
            <input type="text" name="display_name" class="form-control" value="{{ isset($permission) ? $permission->display_name : ''}}">
        </div>

         <div class="col-sm-6">
            <label for="">Permission</label>
            <input type="text" name="name" class="form-control" value="{{ isset($permission) ? $permission->name : ''}}">
        </div>
    </div>
</div>
<div class="form-group">
    <label for="resource">
        <input type="checkbox" name="resource" id="resource">
        Add resource Permission
    </label>
</div>

resources/views/admin/permission/index.blade.php
@extends('back-end.template')
@section('title','List of Permissions')
@section('content')

<div class="page-header">
    <h3 class="page-title">
        List of Permissions
    </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Permissions</a></li>
        <li class="breadcrumb-item active" aria-current="page">All Permissions</li>
        </ol>
    </nav>
    </div>
    <div class="row">  
        <div class="col-md-12">
            <div class="card card-default card-demo" id="cardChart9">
                <div class="card-header">
                    <div class="float-right">
                        @can('add_permission')
                            <a href="{{ route('permission.create') }}" class="btn btn-info btn-sm" data-toggle="tooltip" title="Add new permission"><i class="fa fa-plus"></i> New permission</a>
                        @endcan
                    </div>
                    <div class="card-title">List of permissions</div>
                </div>
                <div class="card-wrapper collapse show">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table display nowrap" datatable style="font-size:12px">
                            <thead>
                                <tr>
                                    <th>Module</th>
                                    <th>Permission</th>
                                    <th>name</th>
                                    @can('edit_permission')
                                        <th>Action</th>
                                    @endcan
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($permissions as $permission)
                                    <tr>
                                        <td>{{$permission->module->name}}</td>
                                        <td>{{$permission->display_name}}</td>
                                        <td>{{$permission->name}}</td>
                                        @can('edit_permission')
                                        <td>
                                            <a href="{{route('permission.edit',$permission->id)}}" class="btn btn-sm btn-info"><i class="fa fa-pencil-alt"></i></a>
                                            <a href="{{route('permission.destroy',$permission->id)}}" class="btn btn-sm btn-warning ajax-delete" data-set="tr"><i class="fa fa-trash"></i></a>
                                        </td>
                                        @endcan
                                    </tr>
                                @endforeach
                            
                            </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@stop