routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/cat', function () {
//     // Artisan::call('migrate');
//     return view('front-end.pages.sigleview.blade');
// });



Route::get('/', function () {
    // Artisan::call('migrate');
    return view('front-end.coming-soon.index');
})->name('index');

Route::get('/contact', function () {
    // Artisan::call('migrate');
    return view('front-end.pages.contact');
})->name('contact');
Route::get('post-publish', 'Admin\PostPublishController@postpublish');


Route::get('/config-cache',function(){
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    Artisan::call('queue:restart');
});

Route::get('/file',function(){
    Artisan::call('queue:work',['--stop-when-empty' => true]);


});

Route::get('/mig', function () {
    Artisan::call('migrate');
    // return 'success';
    // return view('front-end.pages.sigleview.blade');
});

Route::get('/test', function () {
    

    for ($i=0; $i <count(pageTokens()) ; $i++) { 
        // \App\Jobs\SendPost::dispatch(pageTokens()[$i]);

        Toolkito\Larasap\SendTo::Facebook(
            'link',
            [
                'link' =>'http://topcini.com',
                'message' => ' Added at Topcini',
                'page_access_token' => pageTokens()[$i]
            ]
        );
        

    }

    // \App\Jobs\SendPost::dispatch();
});

// Route::get('config-cache',function(){
//     Artisan::call('config:cache');
//     Artisan::call('view:clear');
//     return 'success';
// });


// Auth::routes();


$this->get('aurait', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('aurait', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');


Route::get('/home', 'HomeController@index')->name('home');

Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');


Route::name('password.edit')->get('password-change', 'Admin\UserController@passwordReset');
Route::name('password.update')->post('password-change', 'Admin\UserController@postPasswordReset');

Route::name('password.editadmin')->get('/password-change', 'Admin\UserController@passwordResetadmin');
Route::name('password.update')->post('/password-change', 'Admin\UserController@postPasswordReset');

Route::name('password.request')->get('/password-request', 'Admin\UserController@passwordChange');
Route::name('password.request')->post('/password-request', 'Admin\UserController@postPasswordChange');

Route::group(['prefix'=>'admin','middleware' => ['auth']], function(){
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('comments', 'Admin\CommentsController');
    Route::resource('subscribers', 'Admin\SubscriberController');
    Route::resource('contacts', 'Admin\ContactController');
    Route::resource('post', 'Admin\PostController');
    Route::get('search', 'Front\TechFascinoController@backendsearch')->name('search');

    
   
});

Route::group(['middleware' => ['auth']], function(){
   
    Route::resource('permission', 'Admin\PermissionController');
    Route::resource('role', 'Admin\RoleController');
    Route::resource('user', 'Admin\UserController');
});



// Route::get('/page', 'GraphController@publishToPage')->name('fb');

Route::post('child', 'Admin\PostController@child')->name('child');
// ///////////////////////////////////////////////////////////////

//// Route::get('/', 'Front\TechFascinoController@index')->name('index');
Route::post('savecomment', 'Front\TechFascinoController@savecomment')->name('savecomment');
Route::post('subscribe', 'Front\TechFascinoController@subscribe')->name('subscribe');

Route::post('contact', 'Front\TechFascinoController@contact')->name('contactform');

Route::get('searchresults', 'Front\TechFascinoController@searchresults')->name('searchresults');

Route::get('/{slug?}', 'Front\TechFascinoController@categoryview')->name('category');
Route::get('/{categoryslug?}/{postslug?}', 'Front\TechFascinoController@singlepost')->name('singlepost');

// Route::get('/{category?}/{drama?}', 'Front\TopciniController@singledrama')->name('singledrama');

// Route::get('/{category?}/{drama?}/{postdrama?}', 'Front\TopciniController@singleserial')->name('singleserial');

// Route::post('autocomplete', 'Front\TopciniController@autocomplete')->name('autocomplete');

Route::get('test-email', 'Admin\JobController@processQueue');

Route::get('/', 'Front\TechFascinoController@index')->name('index');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable,HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Models\{Role,Channeling,Revision};
use App\Authorizable;
use Hash,DB;

class UserController extends Controller
{
    use Authorizable;
    public function index()
    {
        $users = User::get();
        return view('admin.user.index',compact('users'));
    }

    public function create()
    {
        $roles = Role::pluck('name','id');
        return view('admin.user.create',compact('roles'));
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
            'roles' => 'required|min:1'
        ]);

        // hash password
        $request->merge(['password' => bcrypt($request->get('password'))]);

            // Create the user
            if ( $user = User::create($request->except('roles', 'permissions')) ) {
                $this->syncPermissions($request, $user);
                // flash('User has been created.');
            } else {
                // flash()->error('Unable to create user.');
            }

        return redirect()->route('user.index');
    }


    public function show($id)
    {
        //
    }


    public function edit(User $user)
    {
        $roles = Role::userData()->pluck('name','id');
        return view('admin.user.edit',compact('roles','user'));
    }


    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users,email,' . $id,
            'roles' => 'required|min:1'
        ]);

        // Get the user
        $user = User::findOrFail($id);

        // Update user
        $user->fill($request->except('roles', 'permissions', 'password'));

        // check for password change
        if($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        // Handle the user roles
        $this->syncPermissions($request, $user);

        $user->save();

        return redirect()->route('user.index');
    }

    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        
        return response()->json([
            'success'=>true,
            'message'=>'deleted success',
            'refresh'=>true,
        ]);
    }

    private function syncPermissions(Request $request, $user)
    {
        // Get the submitted roles
        $roles = $request->get('roles', []);
        $permissions = $request->get('permissions', []);

        // Get the roles
        $roles = Role::find($roles);

        // check for current role changes
        if( ! $user->hasAllRoles( $roles ) ) {
            // reset all direct permissions for user
            $user->permissions()->sync([]);
        } else {
            // handle permissions
            $user->syncPermissions($permissions);
        }

        $user->syncRoles($roles);
        return $user;
    }

    public function passwordReset()
    {
        return view('admin.user.password',['user'=>auth()->user()]);
    }

    public function postPasswordReset(Request $request)
    {
        $user = $request->user();
        $rules = array(
            'old_password' => 'required',
            'password' => 'required|string|min:6|confirmed',
        );
        $this->validate($request, $rules);
        if (!Hash::check($request->old_password, $user->password)) {
            return redirect()->back()->withErrors('Your old password does not match.');

        } else {
            $user->password = bcrypt($request->password);
            $user->save();
            auth()->login($user);
            session()->flash('info','Your password has been changed.');
            return redirect()->route('admin');
        }
    }

    public function userTrack()
    {
        $date = isset(request()->date) ? request()->date : stoday();
        $users = User::whereHas('revisions',function($q) use ($date){
                    $q->whereDate('created_at',$date);
                })->get();
        $params = [
            'users'=>$users,
            'date'=>$date 
        ];
        return view('admin.user.user_track',$params);
    }
}

resources/views/admin/user/create.blade.php
@extends('back-end.template')
@section('title','New User')
@section('content')

<div class="page-header">
    <h3 class="page-title">
        New Users
    </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Users</a></li>
        <li class="breadcrumb-item active" aria-current="page">New Users</li>
        </ol>
    </nav>
    </div>
    <div class="row">  
        <div class="col-md-12">
            <div class="card card-default card-demo" id="cardChart9">
                <div class="card-header">
                    <div class="card-title">New Users</div>
                </div>
                <div class="card-wrapper collapse show">
                    <div class="card-body">
                        {{Form::open(['route'=>['user.store'],'class'=>'user'])}}
                            @include('admin.user.form')
                            <div class="">
                                <a class="btn btn-default" href="{{ route('user.index') }}"> <i class="ion-ios-arrow-thin-left"></i> Back</a>
                                <button class="btn btn-primary">Save</button>
                            </div><!-- form-layout-footer -->
                        {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div>

@stop

resources/views/admin/user/edit.blade.php
@extends('back-end.template')
@section('title','Edit User')
@section('content')

<div class="page-header">
    <h3 class="page-title">
        Edit user
    </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Users</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit user</li>
        </ol>
    </nav>
    </div>
    <div class="row">  
        <div class="col-md-12">
            <div class="card card-default card-demo" id="cardChart9">
                <div class="card-header">
                    <div class="card-title">Edit user - {{ $user->name }}</div>
                </div>
                <div class="card-wrapper collapse show">
                    <div class="card-body">
                        {{Form::model($user,['route'=>['user.update',$user],'class'=>'user','method'=>'patch'])}}
                            @include('admin.user.form')
                            <div class="">
                                <a class="btn btn-default" href="{{ route('user.index') }}"> <i class="ion-ios-arrow-thin-left"></i> Back</a>
                                <button class="btn btn-primary">Update</button>
                            </div><!-- form-layout-footer -->
                        {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div> 
@stop

resources/views/admin/user/form.blade.php
<div class="row">
    <div class="col-sm-6">
        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            <label for="name" class="control-label">Name</label>
            <input id="name" type="text" class="form-control" name="name" value="{{ isset($user) ? $user->name : '' }}" required autofocus>

            @if ($errors->has('name'))
                <span class="help-block">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="col-sm-6">
        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
            <label for="email" class="control-label">E-Mail Address</label>
            <input id="email" type="email" class="form-control" name="email" value="{{ isset($user) ? $user->email : '' }}" required>
            @if ($errors->has('email'))
                <span class="help-block">
                    <strong>{{ $errors->first('email') }}</strong>
                </span>
            @endif
        </div>
    </div>

   
    
</div>
<div class="form-group @if ($errors->has('roles')) has-error @endif">
    {!! Form::label('roles[]', 'Roles for this user') !!}
    {!! Form::select('roles[]', $roles, isset($user) ? $user->roles->pluck('id')->toArray() : null,  ['class' => 'form-control select', 'multiple']) !!}
    @if ($errors->has('roles')) <p class="help-block">{{ $errors->first('roles') }}</p> @endif
</div>


<div class="row">
    <div class="col-sm-6">
        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
            <label for="password" class="control-label">Password</label>
            <input id="password" type="password" class="form-control" name="password">
            @if ($errors->has('password'))
                <span class="help-block">
                    <strong>{{ $errors->first('password') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="col-sm-6">
        <div class="form-group">
            <label for="password-confirm" class="control-label">Confirm Password</label>
            <input id="password-confirm" type="password" class="form-control" name="password_confirmation">
        </div>
    </div>

</div>

resources/views/admin/user/index.blade.php
@extends('back-end.template')
@section('title','List of users')
@section('content')

<div class="page-header">
    <h3 class="page-title">
        List of Users
    </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Users</a></li>
        <li class="breadcrumb-item active" aria-current="page">All Users</li>
        </ol>
    </nav>
    </div>
    <div class="row">  
        <div class="col-md-12">
            <div class="card card-default card-demo" id="cardChart9">
                <div class="card-header">
                    <div class="float-right">
                        @can('add_user')
                            <a href="{{ route('user.create') }}" class="btn btn-info btn-sm" data-toggle="tooltip" title="Add new User"><i class="fa fa-plus"></i> New User</a>
                        @endcan
                    </div>
                    <div class="card-title">List of Users</div>
                </div>
                <div class="card-wrapper collapse show">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table datatable  class="table display nowrap">
                                <thead>
                                        <tr>
                                        <th>Name</th>
                                        <th>Role</th>
                                        <th>Email ID</th>
                                        <th>Created At</th>
                                            @can('edit_user', 'delete_users')
                                                <th>Actions</th>
                                            @endcan
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($users as $user)
                                        @if(!$user->hasRole('SAdmin'))
                                            <tr>
                                            <td>{{$user->name}}</td>
                                            <td>{{ $user->roles->implode('name', ', ') }}</td>
                                            <td>{{$user->email}}</td>
                                            <td>{{ $user->created_at->toFormattedDateString() }}</td>
                                            @can('edit_user')
                                                <td>
                                                    <a href="{{route('user.edit',$user->id)}}" class="btn btn-sm btn-info"><i class="fa fa-pencil-alt"></i></a>
                                                    <a href="{{route('user.destroy',$user->id)}}" class="btn btn-sm btn-warning ajax-delete" data-set="tr"><i class="fa fa-trash"></i></a>
                                                </td>
                                            @endcan
                                            </tr>
                                        @endif
                                    @endforeach
                                    </tbody>
                            
                                </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@push('script')
<script>
  $(document).ready(function(){
    datatableJs();
  });
</script>

@endpush

@stop

resources/views/admin/user/password.blade.php
@extends('back-end.template')
@section('title','Change Password')
@section('content')

<div class="page-header">
    <h3 class="page-title">
        Password
    </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
        <li class="breadcrumb-item" aria-current="page"><a href="{{ route('user.index') }}">User</a></li>
        <li class="breadcrumb-item active">
            <strong>Create</strong>
        </li>
        </ol>
    </nav>
    </div>
    <div class="row">  
        <div class="col-md-12">
            <div class="card card-default card-demo" id="cardChart9">
                <div class="card-header">
                    <div class="card-title">Change Password</div>
                </div>
                <div class="card-wrapper collapse show">
                    <div class="card-body">
                        <div class="ibox-content">
                                {{Form::model($user,['route'=>'password.update'])}}
                                    <div class="row">
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label for="name" class="control-label">Old Password</label>
                                                <input id="name" type="password" class="form-control" name="old_password" required autofocus>
        
                                                @if ($errors->has('old_password'))
                                                    <span class="help-block">
                                                        <strong>{{ $errors->first('old_password') }}</strong>
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
        
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label for="name" class="control-label">New Password</label>
                                                <input id="name" type="password" class="form-control" name="password" required autofocus>
        
                                                @if ($errors->has('password'))
                                                    <span class="help-block">
                                                        <strong>{{ $errors->first('password') }}</strong>
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
        
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label for="name" class="control-label">Confirm Password</label>
                                                <input id="name" type="password" class="form-control" name="password_confirmation" required autofocus>
        
                                                @if ($errors->has('password_con
                                                firmation'))
                                                    <span class="help-block">
                                                        <strong>{{ $errors->first('password_confirmation') }}</strong>
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
        
                                    </div>
        
                                <div class="">
                                    <a class="btn btn-default" href="{{ url('/') }}"> <i class="ion-ios-arrow-thin-left"></i> Back</a>
                                    <button class="btn btn-primary">Reset</button>
                                </div><!-- form-layout-footer -->
                            {{Form::close()}}
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>























   
@stop